name: economyplus
main: me.economyshop.Main
version: 1.0
api-version: 1.16.5
commands:
  shop:
    description: Market açar.
  market:
    description: Market açar.
  pay:
    description: Para gönderir.